name: Build and Push Docker Image to GAR

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: core-dev-435517
  GAR_LOCATION: us-central1
  GAR_REPOSITORY: transcription-container
  IMAGE_NAME: inference-ga

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK and Authenticate with Service Account
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Configure Docker to Authenticate with GAR
      - name: Configure Docker to use GAR
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      # Step 5: Push the Docker image to GAR
      - name: Push Docker image to GAR
        run: |
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # Step 6: Verify Docker Image
      - name: Verify Image Exists in GAR
        run: |
          gcloud artifacts docker images list ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}
